// Mock data for Classroom module
import type {
  User,
  Class,
  CCAClass,
  Student,
  AttendanceRecord,
  ClassAlert,
  ActivityLog,
  ClassOverviewStats,
} from '@/types/classroom'

// Import Eric's comprehensive records
export { ericStudentRecords, getEricRecordsByType, getEricRecentRecords, getEricCounselingSessions, getEricTermlyCheckIns, getEricPTMPrepNotes } from './eric-records'

// Current logged-in user (Form Teacher for 5A, Subject Teacher for 6B and 7A)
export const currentUser: User = {
  user_id: 'teacher-001',
  name: 'Daniel Tan',
  email: 'daniel.tan@school.edu.sg',
  role: 'FormTeacher',
  department: 'Mathematics',
  classes_assigned: ['class-5a', 'class-6b', 'class-7a'],
  form_class_id: 'class-5a',
  cca_classes: ['cca-math-club', 'cca-robotics'],
  avatar: 'DT',
}

// Mock Classes
export const mockClasses: Class[] = [
  {
    class_id: 'class-5a',
    class_name: '5A',
    subject: 'Mathematics',
    year_level: 5,
    teacher_id: 'teacher-001',
    form_teacher_id: 'teacher-001',
    students: [], // Will populate with student IDs
    schedule: [
      { day: 'Monday', start_time: '08:00', end_time: '09:00', location: 'Room 3-12' },
      { day: 'Wednesday', start_time: '08:00', end_time: '09:00', location: 'Room 3-12' },
      { day: 'Friday', start_time: '08:00', end_time: '09:00', location: 'Room 3-12' },
    ],
    academic_year: '2025',
    is_form_class: true,
    student_count: 30,
  },
  {
    class_id: 'class-6b',
    class_name: '6B',
    subject: 'Mathematics',
    year_level: 6,
    teacher_id: 'teacher-001',
    form_teacher_id: 'teacher-002',
    students: [],
    schedule: [
      { day: 'Tuesday', start_time: '09:00', end_time: '10:00', location: 'Room 3-12' },
      { day: 'Thursday', start_time: '09:00', end_time: '10:00', location: 'Room 3-12' },
    ],
    academic_year: '2025',
    is_form_class: false,
    student_count: 28,
  },
  {
    class_id: 'class-7a',
    class_name: '7A',
    subject: 'Mathematics',
    year_level: 7,
    teacher_id: 'teacher-001',
    form_teacher_id: 'teacher-003',
    students: [],
    schedule: [
      { day: 'Monday', start_time: '10:00', end_time: '11:00', location: 'Room 3-12' },
      { day: 'Wednesday', start_time: '10:00', end_time: '11:00', location: 'Room 3-12' },
      { day: 'Friday', start_time: '10:00', end_time: '11:00', location: 'Room 3-12' },
    ],
    academic_year: '2025',
    is_form_class: false,
    student_count: 30,
  },
]

// Mock CCA Classes
export const mockCCAClasses: CCAClass[] = [
  {
    cca_id: 'cca-math-club',
    name: 'Math Olympiad Club',
    type: 'Clubs',
    teacher_in_charge: 'teacher-001',
    members: ['student-001', 'student-003', 'student-005', 'student-007', 'student-009',
              'student-011', 'student-013', 'student-015', 'student-017', 'student-019',
              'student-021', 'student-023'],
    schedule: [
      { day: 'Thursday', start_time: '15:00', end_time: '17:00', location: 'Math Lab' },
    ],
  },
  {
    cca_id: 'cca-robotics',
    name: 'Robotics Club',
    type: 'Clubs',
    teacher_in_charge: 'teacher-001',
    members: ['student-002', 'student-004', 'student-006', 'student-008', 'student-010',
              'student-012', 'student-014', 'student-016', 'student-018', 'student-020'],
    schedule: [
      { day: 'Tuesday', start_time: '15:00', end_time: '17:00', location: 'Computer Lab 2' },
      { day: 'Friday', start_time: '14:00', end_time: '16:00', location: 'Computer Lab 2' },
    ],
  },
]

// Mock Students for Class 5A (Form Class)
export const mockStudents5A: Student[] = [
  {
    student_id: 'student-001',
    name: 'Alice Wong',
    class_id: 'class-5a',
    class_name: 'S2-A',
    year_level: 8,
    status: 'None', // Express stream
    conduct_grade: 'Excellent',
    grades: { english: 92, math: 88, science: 90, chinese: 85, humanities: 87 }, // Recent English A - major improvement
    attendance_rate: 98,
    parent_name: 'Mr. & Mrs. Wong',
    parent_email: 'wong.family@email.com',
    parent_phone: '+65 9123 4567',
    family_background: 'Supportive parents, both working professionals. Younger sibling in primary school.',
    friends: ['Emily Tan', 'Sarah Lee', 'Priya Krishnan'],
    has_medical_conditions: false,
    needs_counselling: false,
    has_disciplinary_issues: false,
    has_sen: false,
  },
  {
    student_id: 'student-002',
    name: 'David Chen',
    class_id: 'class-5a',
    class_name: '5A',
    year_level: 5,
    status: 'None',
    conduct_grade: 'Good',
    grades: { english: 62, math: 58, science: 55 },
    attendance_rate: 85,
    parent_name: 'Mrs. Chen',
    parent_email: 'chen.family@email.com',
    parent_phone: '+65 9234 5678',
    health_declaration: 'No known allergies',
    friends: ['Michael Wong'],
    has_medical_conditions: false,
    needs_counselling: true,
    has_disciplinary_issues: false,
    has_sen: false,
  },
  {
    student_id: 'student-003',
    name: 'Emily Tan',
    class_id: 'class-5a',
    class_name: '5A',
    year_level: 5,
    status: 'None',
    conduct_grade: 'Very Good',
    grades: { english: 85, math: 82, science: 87 },
    attendance_rate: 100,
    parent_name: 'Mr. & Mrs. Tan',
    parent_email: 'tan.family@email.com',
    parent_phone: '+65 9345 6789',
    health_declaration: 'Asthma - requires inhaler during physical activities',
    friends: ['Alice Wong', 'Sarah Lee'],
    has_medical_conditions: true,
    needs_counselling: false,
    has_disciplinary_issues: false,
    has_sen: false,
  },
  {
    student_id: 'student-004',
    name: 'Lim Hui Ling',
    class_id: 'class-5a',
    class_name: '5A',
    year_level: 5,
    status: 'SEN',
    conduct_grade: 'Good',
    grades: { english: 79, math: 85, science: 91 },
    attendance_rate: 92,
    parent_name: 'Mrs. Lim',
    parent_email: 'lim.family@email.com',
    parent_phone: '+65 9456 7890',
    friends: ['Priya Krishnan'],
    has_medical_conditions: false,
    needs_counselling: true,
    has_disciplinary_issues: false,
    has_sen: true,
  },
  {
    student_id: 'student-005',
    name: 'Muhammad Iskandar',
    class_id: 'class-5a',
    class_name: '5A',
    year_level: 5,
    status: 'GEP',
    conduct_grade: 'Excellent',
    grades: { english: 92, math: 95, science: 95 },
    attendance_rate: 98,
    parent_name: 'Mr. & Mrs. Iskandar',
    parent_email: 'iskandar.family@email.com',
    parent_phone: '+65 9567 8901',
    friends: ['John Smith', 'Sarah Lee'],
    has_medical_conditions: false,
    needs_counselling: false,
    has_disciplinary_issues: false,
    has_sen: false,
  },
  {
    student_id: 'student-006',
    name: 'Sarah Lee',
    class_id: 'class-5a',
    class_name: '5A',
    year_level: 5,
    status: 'None',
    conduct_grade: 'Excellent',
    grades: { english: 88, math: 90, science: 86 },
    attendance_rate: 96,
    parent_name: 'Mr. & Mrs. Lee',
    parent_email: 'lee.family@email.com',
    parent_phone: '+65 9678 9012',
    friends: ['Alice Wong', 'Emily Tan'],
    has_medical_conditions: false,
    needs_counselling: false,
    has_disciplinary_issues: false,
    has_sen: false,
  },
  {
    student_id: 'student-007',
    name: 'Priya Krishnan',
    class_id: 'class-5a',
    class_name: '5A',
    year_level: 5,
    status: 'None',
    conduct_grade: 'Very Good',
    grades: { english: 84, math: 87, science: 82 },
    attendance_rate: 94,
    parent_name: 'Dr. & Mrs. Krishnan',
    parent_email: 'krishnan.family@email.com',
    parent_phone: '+65 9789 0123',
    friends: ['Lim Hui Ling'],
    has_medical_conditions: false,
    needs_counselling: false,
    has_disciplinary_issues: false,
    has_sen: false,
  },
  {
    student_id: 'student-008',
    name: 'John Smith',
    class_id: 'class-5a',
    class_name: '5A',
    year_level: 5,
    status: 'GEP',
    conduct_grade: 'Excellent',
    grades: { english: 94, math: 96, science: 93 },
    attendance_rate: 100,
    parent_name: 'Mr. & Mrs. Smith',
    parent_email: 'smith.family@email.com',
    parent_phone: '+65 9890 1234',
    friends: ['Muhammad Iskandar'],
    has_medical_conditions: false,
    needs_counselling: false,
    has_disciplinary_issues: false,
    has_sen: false,
  },
  {
    student_id: 'student-009',
    name: 'Michael Wong',
    class_id: 'class-5a',
    class_name: '5A',
    year_level: 5,
    status: 'None',
    conduct_grade: 'Good',
    grades: { english: 70, math: 68, science: 72 },
    attendance_rate: 88,
    parent_name: 'Mrs. Wong',
    parent_email: 'm.wong@email.com',
    parent_phone: '+65 9901 2345',
    friends: ['David Chen'],
    has_medical_conditions: false,
    needs_counselling: false,
    has_disciplinary_issues: true,
    has_sen: false,
  },
  {
    student_id: 'student-010',
    name: 'Aisha Rahman',
    class_id: 'class-5a',
    class_name: '5A',
    year_level: 5,
    status: 'None',
    conduct_grade: 'Excellent',
    grades: { english: 90, math: 88, science: 92 },
    attendance_rate: 97,
    parent_name: 'Mr. & Mrs. Rahman',
    parent_email: 'rahman.family@email.com',
    parent_phone: '+65 9012 3456',
    friends: [],
    has_medical_conditions: false,
    needs_counselling: false,
    has_disciplinary_issues: false,
    has_sen: false,
  },
  {
    student_id: 'student-011',
    name: 'Ryan Tan',
    class_id: 'class-5a',
    class_name: 'S3-A',
    year_level: 9,
    status: 'None',
    conduct_grade: 'Very Good', // Showing improvement from earlier behavioral issues
    grades: { english: 75, math: 78, science: 72, chinese: 70, humanities: 74 }, // Recent improvement after earlier dip
    attendance_rate: 88, // Improved from earlier issues
    parent_name: 'Mr. Tan',
    parent_email: 'ryan.tan@email.com',
    parent_phone: '+65 9123 4567',
    family_background: 'Single parent household. Father works long hours. Receives CMT support.',
    friends: ['Nathan Goh', 'Lucas Ong'], // Building positive peer relationships
    has_medical_conditions: false,
    needs_counselling: true, // Active CMT interventions
    has_disciplinary_issues: true, // Past classroom disruption case, now showing growth
    has_sen: false,
  },
  {
    student_id: 'student-012',
    name: 'Chloe Ng',
    class_id: 'class-5a',
    class_name: '5A',
    year_level: 5,
    status: 'None',
    conduct_grade: 'Excellent',
    grades: { english: 86, math: 84, science: 88 },
    attendance_rate: 95,
    parent_name: 'Mr. & Mrs. Ng',
    parent_email: 'ng.family@email.com',
    parent_phone: '+65 9234 5678',
    friends: [],
    has_medical_conditions: false,
    needs_counselling: false,
    has_disciplinary_issues: false,
    has_sen: false,
  },
  {
    student_id: 'student-013',
    name: 'Ethan Lim',
    class_id: 'class-5a',
    class_name: '5A',
    year_level: 5,
    status: 'SEN',
    conduct_grade: 'Good',
    grades: { english: 76, math: 80, science: 78 },
    attendance_rate: 90,
    parent_name: 'Mrs. Lim',
    parent_email: 'e.lim@email.com',
    parent_phone: '+65 9345 6789',
    friends: [],
    has_medical_conditions: false,
    needs_counselling: true,
    has_disciplinary_issues: false,
    has_sen: true,
  },
  {
    student_id: 'student-014',
    name: 'Sophia Chan',
    class_id: 'class-5a',
    class_name: '5A',
    year_level: 5,
    status: 'None',
    conduct_grade: 'Excellent',
    grades: { english: 91, math: 89, science: 90 },
    attendance_rate: 98,
    parent_name: 'Mr. & Mrs. Chan',
    parent_email: 'chan.family@email.com',
    parent_phone: '+65 9456 7890',
    friends: [],
    has_medical_conditions: false,
    needs_counselling: false,
    has_disciplinary_issues: false,
    has_sen: false,
  },
  {
    student_id: 'student-015',
    name: 'Nathan Goh',
    class_id: 'class-5a',
    class_name: '5A',
    year_level: 5,
    status: 'None',
    conduct_grade: 'Very Good',
    grades: { english: 80, math: 83, science: 81 },
    attendance_rate: 92,
    parent_name: 'Mr. Goh',
    parent_email: 'goh.family@email.com',
    parent_phone: '+65 9567 8901',
    friends: [],
    has_medical_conditions: false,
    needs_counselling: false,
    has_disciplinary_issues: false,
    has_sen: false,
  },
  {
    student_id: 'student-016',
    name: 'Olivia Teo',
    class_id: 'class-5a',
    class_name: '5A',
    year_level: 5,
    status: 'GEP',
    conduct_grade: 'Excellent',
    grades: { english: 93, math: 94, science: 96 },
    attendance_rate: 99,
    parent_name: 'Dr. Teo',
    parent_email: 'teo.family@email.com',
    parent_phone: '+65 9678 9012',
    friends: [],
    has_medical_conditions: false,
    needs_counselling: false,
    has_disciplinary_issues: false,
    has_sen: false,
  },
  {
    student_id: 'student-017',
    name: 'Daniel Koh',
    class_id: 'class-5a',
    class_name: '5A',
    year_level: 5,
    status: 'None',
    conduct_grade: 'Good',
    grades: { english: 72, math: 70, science: 74 },
    attendance_rate: 87,
    parent_name: 'Mrs. Koh',
    parent_email: 'koh.family@email.com',
    parent_phone: '+65 9789 0123',
    friends: [],
    has_medical_conditions: false,
    needs_counselling: false,
    has_disciplinary_issues: false,
    has_sen: false,
  },
  {
    student_id: 'student-018',
    name: 'Emma Yeo',
    class_id: 'class-5a',
    class_name: '5A',
    year_level: 5,
    status: 'None',
    conduct_grade: 'Excellent',
    grades: { english: 87, math: 86, science: 85 },
    attendance_rate: 96,
    parent_name: 'Mr. & Mrs. Yeo',
    parent_email: 'yeo.family@email.com',
    parent_phone: '+65 9890 1234',
    friends: [],
    has_medical_conditions: false,
    needs_counselling: false,
    has_disciplinary_issues: false,
    has_sen: false,
  },
  {
    student_id: 'student-019',
    name: 'Lucas Ong',
    class_id: 'class-5a',
    class_name: '5A',
    year_level: 5,
    status: 'None',
    conduct_grade: 'Very Good',
    grades: { english: 83, math: 84, science: 82 },
    attendance_rate: 94,
    parent_name: 'Mr. Ong',
    parent_email: 'ong.family@email.com',
    parent_phone: '+65 9901 2345',
    friends: [],
    has_medical_conditions: false,
    needs_counselling: false,
    has_disciplinary_issues: false,
    has_sen: false,
  },
  {
    student_id: 'student-020',
    name: 'Isabella Lau',
    class_id: 'class-5a',
    class_name: '5A',
    year_level: 5,
    status: 'None',
    conduct_grade: 'Excellent',
    grades: { english: 89, math: 91, science: 88 },
    attendance_rate: 97,
    parent_name: 'Mrs. Lau',
    parent_email: 'lau.family@email.com',
    parent_phone: '+65 9012 3456',
    friends: [],
    has_medical_conditions: false,
    needs_counselling: false,
    has_disciplinary_issues: false,
    has_sen: false,
  },
  {
    student_id: 'student-021',
    name: 'Matthew Soh',
    class_id: 'class-5a',
    class_name: '5A',
    year_level: 5,
    status: 'None',
    conduct_grade: 'Good',
    grades: { english: 74, math: 72, science: 76 },
    attendance_rate: 89,
    parent_name: 'Mr. & Mrs. Soh',
    parent_email: 'soh.family@email.com',
    parent_phone: '+65 9123 4567',
    friends: [],
    has_medical_conditions: false,
    needs_counselling: false,
    has_disciplinary_issues: false,
    has_sen: false,
  },
  {
    student_id: 'student-022',
    name: 'Mia Tan',
    class_id: 'class-5a',
    class_name: '5A',
    year_level: 5,
    status: 'None',
    conduct_grade: 'Excellent',
    grades: { english: 85, math: 88, science: 87 },
    attendance_rate: 95,
    parent_name: 'Dr. & Mrs. Tan',
    parent_email: 'mia.tan@email.com',
    parent_phone: '+65 9234 5678',
    friends: [],
    has_medical_conditions: false,
    needs_counselling: false,
    has_disciplinary_issues: false,
    has_sen: false,
  },
  {
    student_id: 'student-023',
    name: 'Joshua Lim',
    class_id: 'class-5a',
    class_name: '5A',
    year_level: 5,
    status: 'GEP',
    conduct_grade: 'Excellent',
    grades: { english: 95, math: 97, science: 94 },
    attendance_rate: 100,
    parent_name: 'Mr. & Mrs. Lim',
    parent_email: 'j.lim@email.com',
    parent_phone: '+65 9345 6789',
    friends: [],
    has_medical_conditions: false,
    needs_counselling: false,
    has_disciplinary_issues: false,
    has_sen: false,
  },
  {
    student_id: 'student-024',
    name: 'Ava Poh',
    class_id: 'class-5a',
    class_name: '5A',
    year_level: 5,
    status: 'None',
    conduct_grade: 'Very Good',
    grades: { english: 81, math: 79, science: 83 },
    attendance_rate: 93,
    parent_name: 'Mrs. Poh',
    parent_email: 'poh.family@email.com',
    parent_phone: '+65 9456 7890',
    friends: [],
    has_medical_conditions: false,
    needs_counselling: false,
    has_disciplinary_issues: false,
    has_sen: false,
  },
  {
    student_id: 'student-025',
    name: 'Benjamin Wee',
    class_id: 'class-5a',
    class_name: '5A',
    year_level: 5,
    status: 'None',
    conduct_grade: 'Good',
    grades: { english: 70, math: 73, science: 71 },
    attendance_rate: 88,
    parent_name: 'Mr. Wee',
    parent_email: 'wee.family@email.com',
    parent_phone: '+65 9567 8901',
    friends: [],
    has_medical_conditions: false,
    needs_counselling: false,
    has_disciplinary_issues: false,
    has_sen: false,
  },
  {
    student_id: 'student-026',
    name: 'Charlotte Ang',
    class_id: 'class-5a',
    class_name: '5A',
    year_level: 5,
    status: 'None',
    conduct_grade: 'Excellent',
    grades: { english: 88, math: 87, science: 89 },
    attendance_rate: 96,
    parent_name: 'Mr. & Mrs. Ang',
    parent_email: 'ang.family@email.com',
    parent_phone: '+65 9678 9012',
    friends: [],
    has_medical_conditions: false,
    needs_counselling: false,
    has_disciplinary_issues: false,
    has_sen: false,
  },
  {
    student_id: 'student-027',
    name: 'James Sim',
    class_id: 'class-5a',
    class_name: '5A',
    year_level: 5,
    status: 'None',
    conduct_grade: 'Very Good',
    grades: { english: 84, math: 82, science: 85 },
    attendance_rate: 94,
    parent_name: 'Mrs. Sim',
    parent_email: 'sim.family@email.com',
    parent_phone: '+65 9789 0123',
    friends: [],
    has_medical_conditions: false,
    needs_counselling: false,
    has_disciplinary_issues: false,
    has_sen: false,
  },
  {
    student_id: 'student-028',
    name: 'Amelia Chong',
    class_id: 'class-5a',
    class_name: '5A',
    year_level: 5,
    status: 'SEN',
    conduct_grade: 'Good',
    grades: { english: 75, math: 78, science: 76 },
    attendance_rate: 91,
    parent_name: 'Mr. & Mrs. Chong',
    parent_email: 'chong.family@email.com',
    parent_phone: '+65 9890 1234',
    friends: [],
    has_medical_conditions: false,
    needs_counselling: true,
    has_disciplinary_issues: false,
    has_sen: true,
  },
  {
    student_id: 'student-029',
    name: 'Alexander Ho',
    class_id: 'class-5a',
    class_name: '5A',
    year_level: 5,
    status: 'None',
    conduct_grade: 'Excellent',
    grades: { english: 90, math: 92, science: 91 },
    attendance_rate: 98,
    parent_name: 'Dr. Ho',
    parent_email: 'ho.family@email.com',
    parent_phone: '+65 9901 2345',
    friends: [],
    has_medical_conditions: false,
    needs_counselling: false,
    has_disciplinary_issues: false,
    has_sen: false,
  },
  {
    student_id: 'student-030',
    name: 'Grace Loh',
    class_id: 'class-5a',
    class_name: '5A',
    year_level: 5,
    status: 'None',
    conduct_grade: 'Very Good',
    grades: { english: 86, math: 85, science: 84 },
    attendance_rate: 95,
    parent_name: 'Mr. & Mrs. Loh',
    parent_email: 'loh.family@email.com',
    parent_phone: '+65 9012 3456',
    friends: [],
    has_medical_conditions: false,
    needs_counselling: false,
    has_disciplinary_issues: false,
    has_sen: false,
  },
  {
    student_id: 'student-031',
    name: 'Eric Lim',
    class_id: 'class-5a',
    class_name: 'S2-A', // Secondary 2, Express Stream
    year_level: 8,
    status: 'SWAN', // SWAN - Student With Additional Needs (Mental Health)
    conduct_grade: 'Good', // Maintaining despite emotional challenges
    grades: {
      english: 65,
      math: 68,
      science: 62,
      chinese: 60,
      humanities: 64,
    }, // Significant decline from Term 2 baseline (78% avg → 64% avg, -14 pts)
    attendance_rate: 89, // Regular absences due to stress-related health issues
    parent_name: 'Dr. & Mrs. Lim',
    parent_email: 'lim.family@email.com',
    parent_phone: '+65 9234 5678',
    family_background:
      'High-achieving professional family (both parents have advanced degrees). Older sibling currently excelling in university. Eric experiences constant comparison and very high academic expectations. Financial pressure from long work hours. Limited emotional support at home - communication style is achievement-focused rather than emotion-focused. Recent family tensions noted (possible marital stress). Family counseling recommended at upcoming PTM (Feb 14, 2025).',
    health_declaration:
      'Frequent nurse visits with stress-related psychosomatic complaints (headaches, stomach aches) - 4 visits this term. No chronic physical conditions. Under active SEC monitoring for anxiety and social difficulties since Oct 2024. Currently in bi-weekly counseling sessions with Ms. Sarah Wong (School Counselor).',
    friends: ['Daniel Koh'], // Very small circle, feeling socially isolated
    has_medical_conditions: false, // Physical health is fine; concerns are mental health
    needs_counselling: true, // Active SWAN case - 8 counseling sessions completed, ongoing support
    has_disciplinary_issues: false, // No behavioral issues; Eric is quiet and compliant
    has_sen: true, // SWAN status activated Oct 2024 for mental health support (anxiety/social difficulties)
  },
]

// Mock Attendance Records for today
export const mockAttendanceToday: AttendanceRecord[] = [
  {
    attendance_id: 'att-001',
    student_id: 'student-002',
    class_id: 'class-5a',
    date: '2025-10-08',
    status: 'Absent',
    reason: 'Sick',
    notes: 'Parent called - fever',
    recorded_by: 'teacher-001',
    recorded_at: '2025-10-08T08:15:00Z',
    parent_notified: true,
  },
  {
    attendance_id: 'att-002',
    student_id: 'student-003',
    class_id: 'class-5a',
    date: '2025-10-08',
    status: 'Absent',
    reason: 'Medical Appointment',
    notes: 'Pre-approved',
    recorded_by: 'teacher-001',
    recorded_at: '2025-10-08T08:15:00Z',
    parent_notified: true,
  },
]

// Mock Class Alerts
export const mockClassAlerts: ClassAlert[] = [
  {
    alert_id: 'alert-001',
    class_id: 'class-5a',
    type: 'Academic',
    severity: 'Urgent',
    title: 'Assignment Grading Deadline Tomorrow',
    description: '15 assignments pending grade entry. Deadline: Oct 9, 5:00 PM',
    created_date: '2025-10-08T06:00:00Z',
    due_date: '2025-10-09T17:00:00Z',
    status: 'Active',
    quick_actions: [
      { action_id: 'act-001', label: 'Enter Grades Now', action: '/classroom/class-5a/academic/grades' },
      { action_id: 'act-002', label: 'Request Extension', action: '/classroom/class-5a/academic/grades/extend', variant: 'outline' },
    ],
  },
  {
    alert_id: 'alert-002',
    class_id: 'class-5a',
    student_id: 'student-002',
    type: 'Attendance',
    severity: 'Urgent',
    title: 'Student Excessive Absences',
    description: 'David Chen: 3 consecutive absences. Parent contact required.',
    created_date: '2025-10-08T08:30:00Z',
    status: 'Active',
    quick_actions: [
      { action_id: 'act-003', label: 'Contact Parent', action: '/classroom/class-5a/communication/new' },
      { action_id: 'act-004', label: 'View Attendance', action: '/classroom/class-5a/attendance/view/student-002', variant: 'outline' },
      { action_id: 'act-005', label: 'Create Intervention', action: '/classroom/class-5a/cases/new', variant: 'outline' },
    ],
  },
  {
    alert_id: 'alert-003',
    class_id: 'class-5a',
    student_id: 'student-003',
    type: 'Academic',
    severity: 'High',
    title: 'Declining Performance Alert',
    description: 'Emily Tan: -15% drop in 2 subjects. Requires intervention discussion.',
    created_date: '2025-10-07T14:00:00Z',
    status: 'Active',
    quick_actions: [
      { action_id: 'act-006', label: 'View Performance', action: '/classroom/students/student-003/academic' },
      { action_id: 'act-007', label: 'Schedule Meeting', action: '/classroom/class-5a/communication/schedule', variant: 'outline' },
    ],
  },
  {
    alert_id: 'alert-004',
    class_id: 'class-5a',
    type: 'Administrative',
    severity: 'High',
    title: 'Permission Slips Pending',
    description: '5 students: Field trip consent pending. Deadline: Oct 12',
    created_date: '2025-10-06T10:00:00Z',
    due_date: '2025-10-12T23:59:00Z',
    status: 'Active',
    quick_actions: [
      { action_id: 'act-008', label: 'Send Reminder', action: '/classroom/class-5a/documents/remind' },
      { action_id: 'act-009', label: 'View Status', action: '/classroom/class-5a/documents', variant: 'outline' },
    ],
  },
  {
    alert_id: 'alert-005',
    class_id: 'class-5a',
    type: 'Wellbeing',
    severity: 'Medium',
    title: 'Wellbeing Check-ins Overdue',
    description: '3 students: Last check-in >2 weeks ago',
    created_date: '2025-10-05T09:00:00Z',
    status: 'Active',
    quick_actions: [
      { action_id: 'act-010', label: 'Conduct Check-ins', action: '/classroom/class-5a/wellbeing' },
      { action_id: 'act-011', label: 'View List', action: '/classroom/class-5a/wellbeing/overdue', variant: 'outline' },
    ],
  },
]

// Mock Activity Log
export const mockActivityLog: ActivityLog[] = [
  {
    activity_id: 'activity-001',
    class_id: 'class-5a',
    student_id: 'student-005',
    type: 'Assignment',
    description: 'Assignment submitted (Sarah Lee)',
    performed_by: 'student-005',
    date: '2025-10-08T06:00:00Z',
  },
  {
    activity_id: 'activity-002',
    class_id: 'class-5a',
    student_id: 'student-002',
    type: 'Attendance',
    description: 'Absence recorded (David Chen - Sick)',
    performed_by: 'teacher-001',
    date: '2025-10-08T03:00:00Z',
  },
  {
    activity_id: 'activity-003',
    class_id: 'class-5a',
    type: 'Grade',
    description: 'Quiz 5 grades published (Average: 81%)',
    performed_by: 'teacher-001',
    date: '2025-10-07T00:00:00Z',
  },
  {
    activity_id: 'activity-004',
    class_id: 'class-5a',
    student_id: 'student-010',
    type: 'Case',
    description: 'Behavioral incident (Michael Wong)',
    performed_by: 'teacher-001',
    date: '2025-10-06T00:00:00Z',
  },
]

// Mock Class Overview Stats
export const mockClassOverviewStats: ClassOverviewStats = {
  class_id: 'class-5a',
  date: '2025-10-08',
  attendance: {
    present: 28,
    absent: 2,
    late: 0,
    excused: 0,
    rate: 93.3,
  },
  academic: {
    pending_grades: 15,
    class_average: 78.5,
    upcoming_assessments: 2,
  },
  alerts: {
    urgent: 2,
    high: 3,
    medium: 2,
    low: 0,
    total: 7,
  },
}

// Helper function to get class by ID
export function getClassById(classId: string): Class | undefined {
  return mockClasses.find((c) => c.class_id === classId)
}

// Helper function to get students by class ID
export function getStudentsByClassId(classId: string): Student[] {
  if (classId === 'class-5a') {
    return mockStudents5A
  }
  // Add other classes as needed
  return []
}

// Helper function to get student by name
export function getStudentByName(studentName: string): Student | undefined {
  // Search across all student arrays
  const allStudents = [...mockStudents5A] // Add other class arrays as they're created
  return allStudents.find((student) => student.name === studentName)
}

// Helper function to get student by ID
export function getStudentById(studentId: string): Student | undefined {
  // Search across all student arrays
  const allStudents = [...mockStudents5A] // Add other class arrays as they're created
  return allStudents.find((student) => student.student_id === studentId)
}

// Helper function to get alerts by class ID
export function getAlertsByClassId(classId: string): ClassAlert[] {
  return mockClassAlerts.filter((alert) => alert.class_id === classId && alert.status === 'Active')
}

// Helper function to get activity log by class ID
export function getActivityLogByClassId(classId: string): ActivityLog[] {
  return mockActivityLog.filter((activity) => activity.class_id === classId)
}

// Helper function to get class overview stats
export function getClassOverviewStats(classId: string): ClassOverviewStats | undefined {
  if (classId === 'class-5a') {
    return mockClassOverviewStats
  }
  return undefined
}
