-- Migration: Seed Behavior Observations
-- Description: Generate behavior observations for all 36 students (3-5 per student)
-- Records: ~144 behavior observations

-- Get teacher ID
WITH teacher_info AS (
  SELECT id as teacher_uuid FROM teachers WHERE email = 'daniel.tan@school.edu.sg' LIMIT 1
)

INSERT INTO behaviour_observations (
  student_id, observation_date, category, title, description, severity,
  location, action_taken, requires_follow_up, follow_up_date, observed_by
)
SELECT
  s.id,
  o.observation_date,
  o.category,
  o.title,
  o.description,
  o.severity,
  o.location,
  o.action_taken,
  o.requires_follow_up,
  o.follow_up_date,
  t.teacher_uuid
FROM students s
CROSS JOIN teacher_info t
CROSS JOIN LATERAL (
  VALUES
    ('2025-10-05'::date, 'undefined', 'Incomplete homework - 3rd occurrence', 'Did not submit Science worksheet. Parent note required.', 'medium', 'Science Lab', 'Spoke to student, sent note to parent', true, '2025-10-19'::date),
    ('2025-09-25'::date, 'undefined', 'Minor peer conflict', 'Argument with classmate over project responsibilities', 'low', 'Classroom', 'Mediated discussion between students', false, NULL),
    ('2025-09-15'::date, 'undefined', 'Incomplete homework - 3rd occurrence', 'Did not submit Science worksheet. Parent note required.', 'medium', 'Science Lab', 'Spoke to student, sent note to parent', true, '2025-09-29'::date),
    ('2025-09-05'::date, 'undefined', 'Incomplete homework - 3rd occurrence', 'Did not submit Science worksheet. Parent note required.', 'medium', 'Science Lab', 'Spoke to student, sent note to parent', true, '2025-09-19'::date),
    ('2025-10-05'::date, 'undefined', 'Inattentive during lessons', 'Frequently distracted, doodling instead of taking notes', 'low', 'Classroom', 'Moved seat closer to front', true, '2025-10-19'::date),
    ('2025-09-25'::date, 'undefined', 'Leadership during group project', 'Organized team effectively and ensured all members contributed', 'low', 'Classroom', NULL, false, NULL),
    ('2025-09-15'::date, 'undefined', 'General observation', 'Student appears tired during morning lessons', 'low', 'Classroom', NULL, false, NULL),
    ('2025-09-05'::date, 'undefined', 'Outstanding class participation', 'Consistently volunteers answers and helps facilitate group discussions', 'low', 'Science Lab', 'Commended by subject teacher', false, NULL),
    ('2025-08-26'::date, 'undefined', 'Leadership during group project', 'Organized team effectively and ensured all members contributed', 'low', 'Classroom', NULL, false, NULL),
    ('2025-10-05'::date, 'undefined', 'Minor peer conflict', 'Argument with classmate over project responsibilities', 'low', 'Classroom', 'Mediated discussion between students', false, NULL),
    ('2025-09-25'::date, 'undefined', 'Inattentive during lessons', 'Frequently distracted, doodling instead of taking notes', 'low', 'Classroom', 'Moved seat closer to front', true, '2025-10-09'::date),
    ('2025-09-15'::date, 'undefined', 'Incomplete homework - 3rd occurrence', 'Did not submit Science worksheet. Parent note required.', 'medium', 'Science Lab', 'Spoke to student, sent note to parent', true, '2025-09-29'::date),
    ('2025-10-05'::date, 'undefined', 'Exceptional peer support', 'Helped struggling classmate with mathematics homework during recess', 'low', 'Classroom', 'Praised in class', false, NULL),
    ('2025-09-25'::date, 'undefined', 'Leadership during group project', 'Organized team effectively and ensured all members contributed', 'low', 'Classroom', NULL, false, NULL),
    ('2025-09-15'::date, 'undefined', 'Leadership during group project', 'Organized team effectively and ensured all members contributed', 'low', 'Classroom', NULL, false, NULL),
    ('2025-09-05'::date, 'undefined', 'Outstanding class participation', 'Consistently volunteers answers and helps facilitate group discussions', 'low', 'Science Lab', 'Commended by subject teacher', false, NULL),
    ('2025-10-05'::date, 'undefined', 'Participation pattern noted', 'More engaged during practical activities than lectures', 'low', 'Science Lab', NULL, false, NULL),
    ('2025-09-25'::date, 'undefined', 'Outstanding class participation', 'Consistently volunteers answers and helps facilitate group discussions', 'low', 'Science Lab', 'Commended by subject teacher', false, NULL),
    ('2025-09-15'::date, 'undefined', 'Incomplete homework - 3rd occurrence', 'Did not submit Science worksheet. Parent note required.', 'medium', 'Science Lab', 'Spoke to student, sent note to parent', true, '2025-09-29'::date),
    ('2025-09-05'::date, 'undefined', 'Inattentive during lessons', 'Frequently distracted, doodling instead of taking notes', 'low', 'Classroom', 'Moved seat closer to front', true, '2025-09-19'::date),
    ('2025-10-05'::date, 'undefined', 'Classroom disruption', 'Repeatedly talking out of turn despite warnings', 'medium', 'Classroom', 'Student given warning, parent contacted', true, '2025-10-19'::date),
    ('2025-09-25'::date, 'undefined', 'Leadership during group project', 'Organized team effectively and ensured all members contributed', 'low', 'Classroom', NULL, false, NULL),
    ('2025-09-15'::date, 'undefined', 'Outstanding class participation', 'Consistently volunteers answers and helps facilitate group discussions', 'low', 'Science Lab', 'Commended by subject teacher', false, NULL),
    ('2025-10-05'::date, 'undefined', 'General observation', 'Student appears tired during morning lessons', 'low', 'Classroom', NULL, false, NULL),
    ('2025-09-25'::date, 'undefined', 'Minor peer conflict', 'Argument with classmate over project responsibilities', 'low', 'Classroom', 'Mediated discussion between students', false, NULL),
    ('2025-09-15'::date, 'undefined', 'Outstanding class participation', 'Consistently volunteers answers and helps facilitate group discussions', 'low', 'Science Lab', 'Commended by subject teacher', false, NULL),
    ('2025-09-05'::date, 'undefined', 'Exceptional peer support', 'Helped struggling classmate with mathematics homework during recess', 'low', 'Classroom', 'Praised in class', false, NULL),
    ('2025-08-26'::date, 'undefined', 'Minor peer conflict', 'Argument with classmate over project responsibilities', 'low', 'Classroom', 'Mediated discussion between students', false, NULL),
    ('2025-10-05'::date, 'undefined', 'Outstanding class participation', 'Consistently volunteers answers and helps facilitate group discussions', 'low', 'Science Lab', 'Commended by subject teacher', false, NULL),
    ('2025-09-25'::date, 'undefined', 'Inattentive during lessons', 'Frequently distracted, doodling instead of taking notes', 'low', 'Classroom', 'Moved seat closer to front', true, '2025-10-09'::date),
    ('2025-09-15'::date, 'undefined', 'Outstanding class participation', 'Consistently volunteers answers and helps facilitate group discussions', 'low', 'Science Lab', 'Commended by subject teacher', false, NULL),
    ('2025-09-05'::date, 'undefined', 'Outstanding class participation', 'Consistently volunteers answers and helps facilitate group discussions', 'low', 'Science Lab', 'Commended by subject teacher', false, NULL),
    ('2025-08-26'::date, 'undefined', 'Exceptional peer support', 'Helped struggling classmate with mathematics homework during recess', 'low', 'Classroom', 'Praised in class', false, NULL),
    ('2025-10-05'::date, 'undefined', 'Participation pattern noted', 'More engaged during practical activities than lectures', 'low', 'Science Lab', NULL, false, NULL),
    ('2025-09-25'::date, 'undefined', 'Participation pattern noted', 'More engaged during practical activities than lectures', 'low', 'Science Lab', NULL, false, NULL),
    ('2025-09-15'::date, 'undefined', 'Classroom disruption', 'Repeatedly talking out of turn despite warnings', 'medium', 'Classroom', 'Student given warning, parent contacted', true, '2025-09-29'::date),
    ('2025-09-05'::date, 'undefined', 'Incomplete homework - 3rd occurrence', 'Did not submit Science worksheet. Parent note required.', 'medium', 'Science Lab', 'Spoke to student, sent note to parent', true, '2025-09-19'::date),
    ('2025-10-05'::date, 'undefined', 'Participation pattern noted', 'More engaged during practical activities than lectures', 'low', 'Science Lab', NULL, false, NULL),
    ('2025-09-25'::date, 'undefined', 'Leadership during group project', 'Organized team effectively and ensured all members contributed', 'low', 'Classroom', NULL, false, NULL),
    ('2025-09-15'::date, 'undefined', 'Incomplete homework - 3rd occurrence', 'Did not submit Science worksheet. Parent note required.', 'medium', 'Science Lab', 'Spoke to student, sent note to parent', true, '2025-09-29'::date),
    ('2025-09-05'::date, 'undefined', 'Incomplete homework - 3rd occurrence', 'Did not submit Science worksheet. Parent note required.', 'medium', 'Science Lab', 'Spoke to student, sent note to parent', true, '2025-09-19'::date),
    ('2025-10-05'::date, 'undefined', 'Minor peer conflict', 'Argument with classmate over project responsibilities', 'low', 'Classroom', 'Mediated discussion between students', false, NULL),
    ('2025-09-25'::date, 'undefined', 'Incomplete homework - 3rd occurrence', 'Did not submit Science worksheet. Parent note required.', 'medium', 'Science Lab', 'Spoke to student, sent note to parent', true, '2025-10-09'::date),
    ('2025-09-15'::date, 'undefined', 'Minor peer conflict', 'Argument with classmate over project responsibilities', 'low', 'Classroom', 'Mediated discussion between students', false, NULL),
    ('2025-09-05'::date, 'undefined', 'Inattentive during lessons', 'Frequently distracted, doodling instead of taking notes', 'low', 'Classroom', 'Moved seat closer to front', true, '2025-09-19'::date),
    ('2025-10-05'::date, 'undefined', 'Exceptional peer support', 'Helped struggling classmate with mathematics homework during recess', 'low', 'Classroom', 'Praised in class', false, NULL),
    ('2025-09-25'::date, 'undefined', 'Leadership during group project', 'Organized team effectively and ensured all members contributed', 'low', 'Classroom', NULL, false, NULL),
    ('2025-09-15'::date, 'undefined', 'Outstanding class participation', 'Consistently volunteers answers and helps facilitate group discussions', 'low', 'Science Lab', 'Commended by subject teacher', false, NULL),
    ('2025-09-05'::date, 'undefined', 'Outstanding class participation', 'Consistently volunteers answers and helps facilitate group discussions', 'low', 'Science Lab', 'Commended by subject teacher', false, NULL),
    ('2025-10-05'::date, 'undefined', 'Incomplete homework - 3rd occurrence', 'Did not submit Science worksheet. Parent note required.', 'medium', 'Science Lab', 'Spoke to student, sent note to parent', true, '2025-10-19'::date),
    ('2025-09-25'::date, 'undefined', 'Leadership during group project', 'Organized team effectively and ensured all members contributed', 'low', 'Classroom', NULL, false, NULL),
    ('2025-09-15'::date, 'undefined', 'Outstanding class participation', 'Consistently volunteers answers and helps facilitate group discussions', 'low', 'Science Lab', 'Commended by subject teacher', false, NULL),
    ('2025-10-05'::date, 'undefined', 'Minor peer conflict', 'Argument with classmate over project responsibilities', 'low', 'Classroom', 'Mediated discussion between students', false, NULL),
    ('2025-09-25'::date, 'undefined', 'Inattentive during lessons', 'Frequently distracted, doodling instead of taking notes', 'low', 'Classroom', 'Moved seat closer to front', true, '2025-10-09'::date),
    ('2025-09-15'::date, 'undefined', 'Minor peer conflict', 'Argument with classmate over project responsibilities', 'low', 'Classroom', 'Mediated discussion between students', false, NULL),
    ('2025-09-05'::date, 'undefined', 'Exceptional peer support', 'Helped struggling classmate with mathematics homework during recess', 'low', 'Classroom', 'Praised in class', false, NULL),
    ('2025-10-05'::date, 'undefined', 'Leadership during group project', 'Organized team effectively and ensured all members contributed', 'low', 'Classroom', NULL, false, NULL),
    ('2025-09-25'::date, 'undefined', 'Leadership during group project', 'Organized team effectively and ensured all members contributed', 'low', 'Classroom', NULL, false, NULL),
    ('2025-09-15'::date, 'undefined', 'Exceptional peer support', 'Helped struggling classmate with mathematics homework during recess', 'low', 'Classroom', 'Praised in class', false, NULL),
    ('2025-09-05'::date, 'undefined', 'Outstanding class participation', 'Consistently volunteers answers and helps facilitate group discussions', 'low', 'Science Lab', 'Commended by subject teacher', false, NULL),
    ('2025-10-05'::date, 'undefined', 'Leadership during group project', 'Organized team effectively and ensured all members contributed', 'low', 'Classroom', NULL, false, NULL),
    ('2025-09-25'::date, 'undefined', 'Outstanding class participation', 'Consistently volunteers answers and helps facilitate group discussions', 'low', 'Science Lab', 'Commended by subject teacher', false, NULL),
    ('2025-09-15'::date, 'undefined', 'Incomplete homework - 3rd occurrence', 'Did not submit Science worksheet. Parent note required.', 'medium', 'Science Lab', 'Spoke to student, sent note to parent', true, '2025-09-29'::date),
    ('2025-10-05'::date, 'undefined', 'Leadership during group project', 'Organized team effectively and ensured all members contributed', 'low', 'Classroom', NULL, false, NULL),
    ('2025-09-25'::date, 'undefined', 'Leadership during group project', 'Organized team effectively and ensured all members contributed', 'low', 'Classroom', NULL, false, NULL),
    ('2025-09-15'::date, 'undefined', 'Outstanding class participation', 'Consistently volunteers answers and helps facilitate group discussions', 'low', 'Science Lab', 'Commended by subject teacher', false, NULL),
    ('2025-09-05'::date, 'undefined', 'Inattentive during lessons', 'Frequently distracted, doodling instead of taking notes', 'low', 'Classroom', 'Moved seat closer to front', true, '2025-09-19'::date),
    ('2025-08-26'::date, 'undefined', 'Incomplete homework - 3rd occurrence', 'Did not submit Science worksheet. Parent note required.', 'medium', 'Science Lab', 'Spoke to student, sent note to parent', true, '2025-09-09'::date),
    ('2025-10-05'::date, 'undefined', 'Exceptional peer support', 'Helped struggling classmate with mathematics homework during recess', 'low', 'Classroom', 'Praised in class', false, NULL),
    ('2025-09-25'::date, 'undefined', 'Participation pattern noted', 'More engaged during practical activities than lectures', 'low', 'Science Lab', NULL, false, NULL),
    ('2025-09-15'::date, 'undefined', 'Exceptional peer support', 'Helped struggling classmate with mathematics homework during recess', 'low', 'Classroom', 'Praised in class', false, NULL),
    ('2025-09-05'::date, 'undefined', 'Exceptional peer support', 'Helped struggling classmate with mathematics homework during recess', 'low', 'Classroom', 'Praised in class', false, NULL),
    ('2025-08-26'::date, 'undefined', 'Exceptional peer support', 'Helped struggling classmate with mathematics homework during recess', 'low', 'Classroom', 'Praised in class', false, NULL),
    ('2025-10-05'::date, 'undefined', 'General observation', 'Student appears tired during morning lessons', 'low', 'Classroom', NULL, false, NULL),
    ('2025-09-25'::date, 'undefined', 'Exceptional peer support', 'Helped struggling classmate with mathematics homework during recess', 'low', 'Classroom', 'Praised in class', false, NULL),
    ('2025-09-15'::date, 'undefined', 'Outstanding class participation', 'Consistently volunteers answers and helps facilitate group discussions', 'low', 'Science Lab', 'Commended by subject teacher', false, NULL),
    ('2025-09-05'::date, 'undefined', 'Exceptional peer support', 'Helped struggling classmate with mathematics homework during recess', 'low', 'Classroom', 'Praised in class', false, NULL),
    ('2025-10-05'::date, 'undefined', 'Participation pattern noted', 'More engaged during practical activities than lectures', 'low', 'Science Lab', NULL, false, NULL),
    ('2025-09-25'::date, 'undefined', 'Participation pattern noted', 'More engaged during practical activities than lectures', 'low', 'Science Lab', NULL, false, NULL),
    ('2025-09-15'::date, 'undefined', 'Minor peer conflict', 'Argument with classmate over project responsibilities', 'low', 'Classroom', 'Mediated discussion between students', false, NULL),
    ('2025-10-05'::date, 'undefined', 'Leadership during group project', 'Organized team effectively and ensured all members contributed', 'low', 'Classroom', NULL, false, NULL),
    ('2025-09-25'::date, 'undefined', 'Exceptional peer support', 'Helped struggling classmate with mathematics homework during recess', 'low', 'Classroom', 'Praised in class', false, NULL),
    ('2025-09-15'::date, 'undefined', 'General observation', 'Student appears tired during morning lessons', 'low', 'Classroom', NULL, false, NULL),
    ('2025-09-05'::date, 'undefined', 'Participation pattern noted', 'More engaged during practical activities than lectures', 'low', 'Science Lab', NULL, false, NULL),
    ('2025-10-05'::date, 'undefined', 'Inattentive during lessons', 'Frequently distracted, doodling instead of taking notes', 'low', 'Classroom', 'Moved seat closer to front', true, '2025-10-19'::date),
    ('2025-09-25'::date, 'undefined', 'Leadership during group project', 'Organized team effectively and ensured all members contributed', 'low', 'Classroom', NULL, false, NULL),
    ('2025-09-15'::date, 'undefined', 'Inattentive during lessons', 'Frequently distracted, doodling instead of taking notes', 'low', 'Classroom', 'Moved seat closer to front', true, '2025-09-29'::date),
    ('2025-10-05'::date, 'undefined', 'Minor peer conflict', 'Argument with classmate over project responsibilities', 'low', 'Classroom', 'Mediated discussion between students', false, NULL),
    ('2025-09-25'::date, 'undefined', 'Exceptional peer support', 'Helped struggling classmate with mathematics homework during recess', 'low', 'Classroom', 'Praised in class', false, NULL),
    ('2025-09-15'::date, 'undefined', 'Outstanding class participation', 'Consistently volunteers answers and helps facilitate group discussions', 'low', 'Science Lab', 'Commended by subject teacher', false, NULL),
    ('2025-10-05'::date, 'undefined', 'Exceptional peer support', 'Helped struggling classmate with mathematics homework during recess', 'low', 'Classroom', 'Praised in class', false, NULL),
    ('2025-09-25'::date, 'undefined', 'Participation pattern noted', 'More engaged during practical activities than lectures', 'low', 'Science Lab', NULL, false, NULL),
    ('2025-09-15'::date, 'undefined', 'Leadership during group project', 'Organized team effectively and ensured all members contributed', 'low', 'Classroom', NULL, false, NULL),
    ('2025-09-05'::date, 'undefined', 'Exceptional peer support', 'Helped struggling classmate with mathematics homework during recess', 'low', 'Classroom', 'Praised in class', false, NULL),
    ('2025-10-05'::date, 'undefined', 'Outstanding class participation', 'Consistently volunteers answers and helps facilitate group discussions', 'low', 'Science Lab', 'Commended by subject teacher', false, NULL),
    ('2025-09-25'::date, 'undefined', 'Outstanding class participation', 'Consistently volunteers answers and helps facilitate group discussions', 'low', 'Science Lab', 'Commended by subject teacher', false, NULL),
    ('2025-09-15'::date, 'undefined', 'Exceptional peer support', 'Helped struggling classmate with mathematics homework during recess', 'low', 'Classroom', 'Praised in class', false, NULL),
    ('2025-09-05'::date, 'undefined', 'Minor peer conflict', 'Argument with classmate over project responsibilities', 'low', 'Classroom', 'Mediated discussion between students', false, NULL),
    ('2025-10-05'::date, 'undefined', 'General observation', 'Student appears tired during morning lessons', 'low', 'Classroom', NULL, false, NULL),
    ('2025-09-25'::date, 'undefined', 'Inattentive during lessons', 'Frequently distracted, doodling instead of taking notes', 'low', 'Classroom', 'Moved seat closer to front', true, '2025-10-09'::date),
    ('2025-09-15'::date, 'undefined', 'Inattentive during lessons', 'Frequently distracted, doodling instead of taking notes', 'low', 'Classroom', 'Moved seat closer to front', true, '2025-09-29'::date),
    ('2025-09-05'::date, 'undefined', 'Minor peer conflict', 'Argument with classmate over project responsibilities', 'low', 'Classroom', 'Mediated discussion between students', false, NULL),
    ('2025-08-26'::date, 'undefined', 'Minor peer conflict', 'Argument with classmate over project responsibilities', 'low', 'Classroom', 'Mediated discussion between students', false, NULL),
    ('2025-10-05'::date, 'undefined', 'Minor peer conflict', 'Argument with classmate over project responsibilities', 'low', 'Classroom', 'Mediated discussion between students', false, NULL),
    ('2025-09-25'::date, 'undefined', 'Minor peer conflict', 'Argument with classmate over project responsibilities', 'low', 'Classroom', 'Mediated discussion between students', false, NULL),
    ('2025-09-15'::date, 'undefined', 'Minor peer conflict', 'Argument with classmate over project responsibilities', 'low', 'Classroom', 'Mediated discussion between students', false, NULL),
    ('2025-10-05'::date, 'undefined', 'Inattentive during lessons', 'Frequently distracted, doodling instead of taking notes', 'low', 'Classroom', 'Moved seat closer to front', true, '2025-10-19'::date),
    ('2025-09-25'::date, 'undefined', 'Leadership during group project', 'Organized team effectively and ensured all members contributed', 'low', 'Classroom', NULL, false, NULL),
    ('2025-09-15'::date, 'undefined', 'Incomplete homework - 3rd occurrence', 'Did not submit Science worksheet. Parent note required.', 'medium', 'Science Lab', 'Spoke to student, sent note to parent', true, '2025-09-29'::date),
    ('2025-10-05'::date, 'undefined', 'Outstanding class participation', 'Consistently volunteers answers and helps facilitate group discussions', 'low', 'Science Lab', 'Commended by subject teacher', false, NULL),
    ('2025-09-25'::date, 'undefined', 'Outstanding class participation', 'Consistently volunteers answers and helps facilitate group discussions', 'low', 'Science Lab', 'Commended by subject teacher', false, NULL),
    ('2025-09-15'::date, 'undefined', 'Inattentive during lessons', 'Frequently distracted, doodling instead of taking notes', 'low', 'Classroom', 'Moved seat closer to front', true, '2025-09-29'::date),
    ('2025-10-05'::date, 'undefined', 'Exceptional peer support', 'Helped struggling classmate with mathematics homework during recess', 'low', 'Classroom', 'Praised in class', false, NULL),
    ('2025-09-25'::date, 'undefined', 'Leadership during group project', 'Organized team effectively and ensured all members contributed', 'low', 'Classroom', NULL, false, NULL),
    ('2025-09-15'::date, 'undefined', 'Inattentive during lessons', 'Frequently distracted, doodling instead of taking notes', 'low', 'Classroom', 'Moved seat closer to front', true, '2025-09-29'::date),
    ('2025-09-05'::date, 'undefined', 'Incomplete homework - 3rd occurrence', 'Did not submit Science worksheet. Parent note required.', 'medium', 'Science Lab', 'Spoke to student, sent note to parent', true, '2025-09-19'::date),
    ('2025-10-05'::date, 'undefined', 'Outstanding class participation', 'Consistently volunteers answers and helps facilitate group discussions', 'low', 'Science Lab', 'Commended by subject teacher', false, NULL),
    ('2025-09-25'::date, 'undefined', 'Leadership during group project', 'Organized team effectively and ensured all members contributed', 'low', 'Classroom', NULL, false, NULL),
    ('2025-09-15'::date, 'undefined', 'Exceptional peer support', 'Helped struggling classmate with mathematics homework during recess', 'low', 'Classroom', 'Praised in class', false, NULL),
    ('2025-09-05'::date, 'undefined', 'Exceptional peer support', 'Helped struggling classmate with mathematics homework during recess', 'low', 'Classroom', 'Praised in class', false, NULL),
    ('2025-08-26'::date, 'undefined', 'Outstanding class participation', 'Consistently volunteers answers and helps facilitate group discussions', 'low', 'Science Lab', 'Commended by subject teacher', false, NULL),
    ('2025-10-05'::date, 'undefined', 'Outstanding class participation', 'Consistently volunteers answers and helps facilitate group discussions', 'low', 'Science Lab', 'Commended by subject teacher', false, NULL),
    ('2025-09-25'::date, 'undefined', 'Classroom disruption', 'Repeatedly talking out of turn despite warnings', 'medium', 'Classroom', 'Student given warning, parent contacted', true, '2025-10-09'::date),
    ('2025-09-15'::date, 'undefined', 'Leadership during group project', 'Organized team effectively and ensured all members contributed', 'low', 'Classroom', NULL, false, NULL),
    ('2025-09-05'::date, 'undefined', 'Outstanding class participation', 'Consistently volunteers answers and helps facilitate group discussions', 'low', 'Science Lab', 'Commended by subject teacher', false, NULL),
    ('2025-08-26'::date, 'undefined', 'Inattentive during lessons', 'Frequently distracted, doodling instead of taking notes', 'low', 'Classroom', 'Moved seat closer to front', true, '2025-09-09'::date),
    ('2025-10-05'::date, 'undefined', 'General observation', 'Student appears tired during morning lessons', 'low', 'Classroom', NULL, false, NULL),
    ('2025-09-25'::date, 'undefined', 'Exceptional peer support', 'Helped struggling classmate with mathematics homework during recess', 'low', 'Classroom', 'Praised in class', false, NULL),
    ('2025-09-15'::date, 'undefined', 'Leadership during group project', 'Organized team effectively and ensured all members contributed', 'low', 'Classroom', NULL, false, NULL),
    ('2025-09-05'::date, 'undefined', 'Inattentive during lessons', 'Frequently distracted, doodling instead of taking notes', 'low', 'Classroom', 'Moved seat closer to front', true, '2025-09-19'::date),
    ('2025-10-05'::date, 'undefined', 'Outstanding class participation', 'Consistently volunteers answers and helps facilitate group discussions', 'low', 'Science Lab', 'Commended by subject teacher', false, NULL),
    ('2025-09-25'::date, 'undefined', 'Minor peer conflict', 'Argument with classmate over project responsibilities', 'low', 'Classroom', 'Mediated discussion between students', false, NULL),
    ('2025-09-15'::date, 'undefined', 'Exceptional peer support', 'Helped struggling classmate with mathematics homework during recess', 'low', 'Classroom', 'Praised in class', false, NULL),
    ('2025-09-05'::date, 'undefined', 'Leadership during group project', 'Organized team effectively and ensured all members contributed', 'low', 'Classroom', NULL, false, NULL),
    ('2025-08-26'::date, 'undefined', 'Exceptional peer support', 'Helped struggling classmate with mathematics homework during recess', 'low', 'Classroom', 'Praised in class', false, NULL),
    ('2025-10-05'::date, 'undefined', 'Incomplete homework - 3rd occurrence', 'Did not submit Science worksheet. Parent note required.', 'medium', 'Science Lab', 'Spoke to student, sent note to parent', true, '2025-10-19'::date),
    ('2025-09-25'::date, 'undefined', 'Leadership during group project', 'Organized team effectively and ensured all members contributed', 'low', 'Classroom', NULL, false, NULL),
    ('2025-09-15'::date, 'undefined', 'Incomplete homework - 3rd occurrence', 'Did not submit Science worksheet. Parent note required.', 'medium', 'Science Lab', 'Spoke to student, sent note to parent', true, '2025-09-29'::date),
    ('2025-09-05'::date, 'undefined', 'Leadership during group project', 'Organized team effectively and ensured all members contributed', 'low', 'Classroom', NULL, false, NULL),
    ('2025-08-26'::date, 'undefined', 'Minor peer conflict', 'Argument with classmate over project responsibilities', 'low', 'Classroom', 'Mediated discussion between students', false, NULL),
    ('2025-10-05'::date, 'undefined', 'Inattentive during lessons', 'Frequently distracted, doodling instead of taking notes', 'low', 'Classroom', 'Moved seat closer to front', true, '2025-10-19'::date),
    ('2025-09-25'::date, 'undefined', 'Outstanding class participation', 'Consistently volunteers answers and helps facilitate group discussions', 'low', 'Science Lab', 'Commended by subject teacher', false, NULL),
    ('2025-09-15'::date, 'undefined', 'Incomplete homework - 3rd occurrence', 'Did not submit Science worksheet. Parent note required.', 'medium', 'Science Lab', 'Spoke to student, sent note to parent', true, '2025-09-29'::date),
    ('2025-09-05'::date, 'undefined', 'Exceptional peer support', 'Helped struggling classmate with mathematics homework during recess', 'low', 'Classroom', 'Praised in class', false, NULL)
) AS o(observation_date, category, title, description, severity, location, action_taken, requires_follow_up, follow_up_date)
WHERE s.student_id IN ('S050101', 'S050102', 'S050103', 'S050104', 'S050105', 'S050106', 'S050107', 'S050108', 'S050109', 'S050110', 'S050111', 'S050112', 'S050032', 'S050033', 'S050034', 'S050035', 'S050036', 'S050037', 'S050038', 'S050039', 'S050040', 'S050041', 'S050042', 'S050043', 'S050044', 'S050045', 'S050046', 'S050047', 'S050048', 'S050049', 'S050050', 'S050051', 'S050052', 'S050053', 'S050054', 'S050055');
