-- Migration: Seed Friend Relationships
-- Description: Generate realistic friend clusters for all 36 students
-- Records: ~108 friend relationships

-- Get teacher ID for observed_by
WITH teacher_info AS (
  SELECT id as teacher_uuid FROM teachers WHERE email = 'daniel.tan@school.edu.sg' LIMIT 1
)

INSERT INTO friend_relationships (
  student_id, friend_id, relationship_type, closeness_level, notes, observed_by, observation_date
)
VALUES
  ((SELECT id FROM students WHERE student_id = 'S050101'), (SELECT id FROM students WHERE student_id = 'S050103'), 'close_friend', 'acquaintance', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050101'), (SELECT id FROM students WHERE student_id = 'S050104'), 'close_friend', 'close', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050101'), (SELECT id FROM students WHERE student_id = 'S050102'), 'close_friend', 'close', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050102'), (SELECT id FROM students WHERE student_id = 'S050104'), 'close_friend', 'acquaintance', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050102'), (SELECT id FROM students WHERE student_id = 'S050101'), 'close_friend', 'close', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050102'), (SELECT id FROM students WHERE student_id = 'S050103'), 'close_friend', 'acquaintance', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050103'), (SELECT id FROM students WHERE student_id = 'S050104'), 'close_friend', 'very_close', 'Best friends since primary 1', (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050103'), (SELECT id FROM students WHERE student_id = 'S050101'), 'close_friend', 'close', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050103'), (SELECT id FROM students WHERE student_id = 'S050102'), 'close_friend', 'acquaintance', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050104'), (SELECT id FROM students WHERE student_id = 'S050102'), 'close_friend', 'acquaintance', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050104'), (SELECT id FROM students WHERE student_id = 'S050103'), 'close_friend', 'acquaintance', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050105'), (SELECT id FROM students WHERE student_id = 'S050106'), 'close_friend', 'very_close', 'Best friends since primary 1', (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050105'), (SELECT id FROM students WHERE student_id = 'S050108'), 'close_friend', 'close', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050105'), (SELECT id FROM students WHERE student_id = 'S050107'), 'close_friend', 'acquaintance', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050106'), (SELECT id FROM students WHERE student_id = 'S050107'), 'close_friend', 'acquaintance', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050106'), (SELECT id FROM students WHERE student_id = 'S050108'), 'close_friend', 'very_close', 'Best friends since primary 1', (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050106'), (SELECT id FROM students WHERE student_id = 'S050105'), 'close_friend', 'very_close', 'Best friends since primary 1', (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050107'), (SELECT id FROM students WHERE student_id = 'S050108'), 'close_friend', 'very_close', 'Best friends since primary 1', (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050107'), (SELECT id FROM students WHERE student_id = 'S050105'), 'close_friend', 'close', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050108'), (SELECT id FROM students WHERE student_id = 'S050107'), 'close_friend', 'very_close', 'Best friends since primary 1', (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050108'), (SELECT id FROM students WHERE student_id = 'S050106'), 'close_friend', 'close', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050108'), (SELECT id FROM students WHERE student_id = 'S050105'), 'close_friend', 'very_close', 'Best friends since primary 1', (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050109'), (SELECT id FROM students WHERE student_id = 'S050112'), 'close_friend', 'close', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050109'), (SELECT id FROM students WHERE student_id = 'S050111'), 'close_friend', 'very_close', 'Best friends since primary 1', (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050109'), (SELECT id FROM students WHERE student_id = 'S050110'), 'close_friend', 'close', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050110'), (SELECT id FROM students WHERE student_id = 'S050112'), 'close_friend', 'acquaintance', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050110'), (SELECT id FROM students WHERE student_id = 'S050109'), 'close_friend', 'close', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050111'), (SELECT id FROM students WHERE student_id = 'S050112'), 'close_friend', 'very_close', 'Best friends since primary 1', (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050111'), (SELECT id FROM students WHERE student_id = 'S050110'), 'close_friend', 'acquaintance', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050111'), (SELECT id FROM students WHERE student_id = 'S050109'), 'close_friend', 'acquaintance', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050112'), (SELECT id FROM students WHERE student_id = 'S050111'), 'close_friend', 'very_close', 'Best friends since primary 1', (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050112'), (SELECT id FROM students WHERE student_id = 'S050109'), 'close_friend', 'very_close', 'Best friends since primary 1', (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050112'), (SELECT id FROM students WHERE student_id = 'S050110'), 'close_friend', 'very_close', 'Best friends since primary 1', (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050032'), (SELECT id FROM students WHERE student_id = 'S050033'), 'close_friend', 'acquaintance', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050032'), (SELECT id FROM students WHERE student_id = 'S050034'), 'close_friend', 'acquaintance', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050032'), (SELECT id FROM students WHERE student_id = 'S050035'), 'close_friend', 'acquaintance', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050033'), (SELECT id FROM students WHERE student_id = 'S050035'), 'close_friend', 'acquaintance', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050033'), (SELECT id FROM students WHERE student_id = 'S050034'), 'close_friend', 'close', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050034'), (SELECT id FROM students WHERE student_id = 'S050035'), 'close_friend', 'acquaintance', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050034'), (SELECT id FROM students WHERE student_id = 'S050032'), 'close_friend', 'close', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050034'), (SELECT id FROM students WHERE student_id = 'S050033'), 'close_friend', 'close', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050035'), (SELECT id FROM students WHERE student_id = 'S050033'), 'close_friend', 'close', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050035'), (SELECT id FROM students WHERE student_id = 'S050034'), 'close_friend', 'very_close', 'Best friends since primary 1', (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050036'), (SELECT id FROM students WHERE student_id = 'S050037'), 'close_friend', 'very_close', 'Best friends since primary 1', (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050036'), (SELECT id FROM students WHERE student_id = 'S050038'), 'close_friend', 'acquaintance', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050037'), (SELECT id FROM students WHERE student_id = 'S050039'), 'close_friend', 'acquaintance', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050037'), (SELECT id FROM students WHERE student_id = 'S050036'), 'close_friend', 'close', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050037'), (SELECT id FROM students WHERE student_id = 'S050038'), 'close_friend', 'very_close', 'Best friends since primary 1', (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050038'), (SELECT id FROM students WHERE student_id = 'S050036'), 'close_friend', 'acquaintance', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050038'), (SELECT id FROM students WHERE student_id = 'S050037'), 'close_friend', 'very_close', 'Best friends since primary 1', (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050038'), (SELECT id FROM students WHERE student_id = 'S050039'), 'close_friend', 'close', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050039'), (SELECT id FROM students WHERE student_id = 'S050038'), 'close_friend', 'very_close', 'Best friends since primary 1', (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050039'), (SELECT id FROM students WHERE student_id = 'S050036'), 'close_friend', 'acquaintance', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050039'), (SELECT id FROM students WHERE student_id = 'S050037'), 'close_friend', 'very_close', 'Best friends since primary 1', (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050040'), (SELECT id FROM students WHERE student_id = 'S050041'), 'close_friend', 'acquaintance', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050040'), (SELECT id FROM students WHERE student_id = 'S050042'), 'close_friend', 'very_close', 'Best friends since primary 1', (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050041'), (SELECT id FROM students WHERE student_id = 'S050040'), 'close_friend', 'acquaintance', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050041'), (SELECT id FROM students WHERE student_id = 'S050043'), 'close_friend', 'close', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050041'), (SELECT id FROM students WHERE student_id = 'S050042'), 'close_friend', 'very_close', 'Best friends since primary 1', (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050042'), (SELECT id FROM students WHERE student_id = 'S050041'), 'close_friend', 'acquaintance', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050042'), (SELECT id FROM students WHERE student_id = 'S050040'), 'close_friend', 'very_close', 'Best friends since primary 1', (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050043'), (SELECT id FROM students WHERE student_id = 'S050041'), 'close_friend', 'very_close', 'Best friends since primary 1', (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050043'), (SELECT id FROM students WHERE student_id = 'S050040'), 'close_friend', 'very_close', 'Best friends since primary 1', (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050044'), (SELECT id FROM students WHERE student_id = 'S050045'), 'close_friend', 'acquaintance', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050044'), (SELECT id FROM students WHERE student_id = 'S050046'), 'close_friend', 'very_close', 'Best friends since primary 1', (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050045'), (SELECT id FROM students WHERE student_id = 'S050046'), 'close_friend', 'very_close', 'Best friends since primary 1', (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050045'), (SELECT id FROM students WHERE student_id = 'S050044'), 'close_friend', 'very_close', 'Best friends since primary 1', (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050046'), (SELECT id FROM students WHERE student_id = 'S050044'), 'close_friend', 'very_close', 'Best friends since primary 1', (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050046'), (SELECT id FROM students WHERE student_id = 'S050047'), 'close_friend', 'acquaintance', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050047'), (SELECT id FROM students WHERE student_id = 'S050044'), 'close_friend', 'acquaintance', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050047'), (SELECT id FROM students WHERE student_id = 'S050045'), 'close_friend', 'close', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050047'), (SELECT id FROM students WHERE student_id = 'S050046'), 'close_friend', 'acquaintance', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050048'), (SELECT id FROM students WHERE student_id = 'S050049'), 'close_friend', 'close', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050048'), (SELECT id FROM students WHERE student_id = 'S050051'), 'close_friend', 'acquaintance', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050049'), (SELECT id FROM students WHERE student_id = 'S050051'), 'close_friend', 'very_close', 'Best friends since primary 1', (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050049'), (SELECT id FROM students WHERE student_id = 'S050048'), 'close_friend', 'very_close', 'Best friends since primary 1', (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050049'), (SELECT id FROM students WHERE student_id = 'S050050'), 'close_friend', 'close', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050050'), (SELECT id FROM students WHERE student_id = 'S050051'), 'close_friend', 'acquaintance', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050050'), (SELECT id FROM students WHERE student_id = 'S050048'), 'close_friend', 'very_close', 'Best friends since primary 1', (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050051'), (SELECT id FROM students WHERE student_id = 'S050049'), 'close_friend', 'acquaintance', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050051'), (SELECT id FROM students WHERE student_id = 'S050050'), 'close_friend', 'acquaintance', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050051'), (SELECT id FROM students WHERE student_id = 'S050048'), 'close_friend', 'close', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050052'), (SELECT id FROM students WHERE student_id = 'S050053'), 'close_friend', 'very_close', 'Best friends since primary 1', (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050052'), (SELECT id FROM students WHERE student_id = 'S050055'), 'close_friend', 'close', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050052'), (SELECT id FROM students WHERE student_id = 'S050054'), 'close_friend', 'close', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050053'), (SELECT id FROM students WHERE student_id = 'S050054'), 'close_friend', 'close', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050053'), (SELECT id FROM students WHERE student_id = 'S050055'), 'close_friend', 'very_close', 'Best friends since primary 1', (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050053'), (SELECT id FROM students WHERE student_id = 'S050052'), 'close_friend', 'close', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050054'), (SELECT id FROM students WHERE student_id = 'S050052'), 'close_friend', 'very_close', 'Best friends since primary 1', (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050054'), (SELECT id FROM students WHERE student_id = 'S050053'), 'close_friend', 'close', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050055'), (SELECT id FROM students WHERE student_id = 'S050053'), 'close_friend', 'acquaintance', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date),
  ((SELECT id FROM students WHERE student_id = 'S050055'), (SELECT id FROM students WHERE student_id = 'S050052'), 'close_friend', 'close', NULL, (SELECT teacher_uuid FROM teacher_info), '2025-09-01'::date);
